### ISSUE TITLE
Spinning wheel of death - uncaught type error

### ISSUE THREAD

**Issue by kahunapule** [sillsdev/appbuilder-pwa#712]
I'm getting a spinning wheel of death trying to load a PWA. Chrome says:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at theme.BiABRSbW.js:4769:22022
    at _ (entry.ArJezRqP.js:6:29330)
    at entry.ArJezRqP.js:6:29445
    at Object.h [as subscribe] (entry.ArJezRqP.js:6:28975)
    at j (scheduler.C8SBejcr.js:1:983)
    at _t (scheduler.C8SBejcr.js:1:1126)
    at kn (0.VoG3hY0s.js:1:63039)
    at Q (index.4FAxb_EP.js:1:1502)
    at new Nn (0.VoG3hY0s.js:1:63793)
    at zt (scheduler.C8SBejcr.js:1:7086)
Examples: https://eBible.org/hatbsa/pwa/
https://eBible.org/eng-web/pwa/
https://ebible.org/engwebu/pwa/
https://ebible.org/spapddpt/pwa/
etc.

**Comment by chrisvire** [comment]
@kahunapule Is this still a problem?

**Comment by judah-sotomayor** [comment]
I am seeing problems on these pages still.

<img width="1598" alt="Image" src="https://github.com/user-attachments/assets/a3dc4213-5e80-49f6-9976-c8245e48ceb4" />

**Comment by judah-sotomayor** [comment]
If you open the pages for the first time, there is no problem. Opening them again results in an issue. Clearing cache and then reloading allows the page to load. I am not sure this is a problem on our end so much as in whatever reverse proxy these sites are using

**Comment by judah-sotomayor** [comment]
Another possibility is there's some issue with the interplay between multiple hosted sites. When I navigate from one to the other, similar problems pop up.
